#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points to your load-balancer IP

domain_info() {
	local domain = "$1"
	local subdomain = "$2"
	local line
	line = $(dig "$subdomain"."$domain" | awk '/ANSWER SECTION:/ {getline; print; getline; print}')
	echo "$subdomain $line | awk '{printf "The subdomain %S is a %s record and points to %s\n", $1, $2, $3}'
}

if [ "$#" -eq 1 ]; then
	domain_info "$1" "www"
	domain_info "$1" "lb-01"
	domain_info "$1" "web-01"
	domain_info "$1" "web-02"

elif [ "$#" -eq 2 ]; then
	domain_info "$1" "$2"
fi
