#!/usr/bin/env bash
# Redirection

sudo apt-get update -y -qq &&/
        sudo apt-get install nginx -y
sudo service nginx start
sudo ufw aloow 'Nginx HTTP'
sudo chown -R "$USER:$USER" /var/www/html
sudo chmod -R 755 /var/www
cp /var/www/index.nginx-debain.html /var/www/html/index.nginx-debain.html.bckp
echo -e "Hello World!" > /var/www/html/index.nginx-debain.html
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/def
sudo service nginx restart
