#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page 
#contains the string Ceci n'est pas une page.

sudo apt-get update -y -qq &&/
	sudo apt-get install nginx -y
sudo service nginx start
sudo ufw aloow 'Nginx HTTP'
sudo chown -R "$USER:$USER" /var/www/html
sudo chmod -R 755 /var/www
cp /var/www/index.nginx-debain.html /var/www/html/index.nginx-debain.html.bckp
echo -e "Hello World!" > /var/www/html/index.nginx-debain.html
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/def
echo "Ceci n'est pas une page" >> /var/www/html/error404.html
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default
sudo service nginx restart
