#!/usr/bin/env bash
# configure web-02 to be identical to web-01

echo -e "Updating some minor checks\n....."

function install() {
	command -v "$1" &> /dev/null

	if [ $? -ne 0 ];then
		echo -e "	installing: $1$\n"
		sudo apt-get update -y -qq && \
			sudo apt-get install -y "$1" -qq
		echo -e "\n"
	else
		echo -e "	${1} is already installed.\n"
	fi
}

# install nginx

echo -e "setting up some import minor\n"

sudo ufw allow 'nginx HTTP'

if [ -d "/var/www" ]; then
	sudo chown -R "$USER:$USER" /var/www
	sudo chmod -R 755 /var/www
else
	sudo mkdir -P /var/www
	sudo chown -R "$USER:$USER" /var/www
	sudo chmod -r 755 /var/www
fi

#create directories if not exists
for dir in /var/www/{html.error}; do
	if ! [ -d "$dir" ]; then
		mkdir -P "$dir"
	fi
done

# crate a new index
echo "Hello World" > /var/www/html/index.html
# crate an error page
echo "Ceci n'est pas una page" > /var/www/html/error_404.html
# backup default server config files
sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup

server config=\
echo "server_config" | sudo dd status=none of=/etc/nginx/sites-enables/default
if [ "$(pgrep -c nginx)" -le 0 ]; then
	sudo service nginx start
else
	sudo service nginx restart
fi
