#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

#install an d config "haproxy"
sudo apt-get -y update
apt-get -y install haproxy

# config the server
server_config=\

echo "$sserver_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to start by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

#testing haproxy 
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

#restart haproxy
sudo service haproxy restart
