#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using while loop
# on the 4th iteration, displays "bad luck" before "Best School"
# on the 8th iteration, displays "good luck" before "Best School"

count=0

while [ $count -lt 10 ]
do
	if [ $count -eq 3 ]
	then
		echo "bad luck"
	elif [ $count -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( count++ ))
done
		
